### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [OXWAZZ/Plugin-QGIS-SPT#1]
# problem

Please remove _pycache folder. it is automatically generated on install.

Also, add a little description of what the plugin does

**Comment by oxwazz** [comment]
thank you for the suggestion, I've added it, I hope it's okay

**Comment by oxwazz** [comment]
@NyakudyaA  is my plugin meets the requirements?

**Comment by NyakudyaA** [comment]
> @NyakudyaA is my plugin meets the requirements?

No yet, the metadata link for issues does not point to the correct URL

**Comment by oxwazz** [comment]
@NyakudyaA i have updated metadata on [this commit](https://github.com/OXWAZZ/Plugin-QGIS-SPT/commit/967614c79f1549429fe57a5a0fa8318000d7393c)
thanks for the help

**Comment by NyakudyaA** [comment]
> @NyakudyaA i have updated metadata on [this commit](https://github.com/OXWAZZ/Plugin-QGIS-SPT/commit/967614c79f1549429fe57a5a0fa8318000d7393c)
> thanks for the help

You need to upload to the plugin repo replacing the version you had

**Comment by oxwazz** [comment]
@NyakudyaA done. i have replacing the version to the plugin repo with the new one
